version: '3'

services:
  datasheet-ai-analyzer:
    build: .
    container_name: datasheet-ai-analyzer
    ports:
      - "1832:1832"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0  # 生产环境设置为0 